var files_dup =
[
    [ "communicationmanager.h", "communicationmanager_8h.html", null ],
    [ "cursor.cpp", "cursor_8cpp.html", null ],
    [ "cursor.h", "cursor_8h.html", "cursor_8h" ],
    [ "cursordata.cpp", "cursordata_8cpp.html", null ],
    [ "cursordata.h", "cursordata_8h.html", "cursordata_8h" ],
    [ "datacommuniaction.cpp", "datacommuniaction_8cpp.html", "datacommuniaction_8cpp" ],
    [ "datacommuniaction.h", "datacommuniaction_8h.html", "datacommuniaction_8h" ],
    [ "fftw3.h", "fftw3_8h.html", "fftw3_8h" ],
    [ "languagesettingsdialog.cpp", "languagesettingsdialog_8cpp.html", null ],
    [ "languagesettingsdialog.h", "languagesettingsdialog_8h.html", "languagesettingsdialog_8h" ],
    [ "main.cpp", "main_8cpp.html", "main_8cpp" ],
    [ "mainwindow.cpp", "mainwindow_8cpp.html", "mainwindow_8cpp" ],
    [ "mainwindow.h", "mainwindow_8h.html", "mainwindow_8h" ],
    [ "oscilloscopechart.cpp", "oscilloscopechart_8cpp.html", "oscilloscopechart_8cpp" ],
    [ "oscilloscopechart.h", "oscilloscopechart_8h.html", "oscilloscopechart_8h" ],
    [ "portsettingsdialog.cpp", "portsettingsdialog_8cpp.html", null ],
    [ "portsettingsdialog.h", "portsettingsdialog_8h.html", "portsettingsdialog_8h" ],
    [ "sample.cpp", "sample_8cpp.html", null ],
    [ "sample.h", "sample_8h.html", "sample_8h" ],
    [ "serialportsettings.cpp", "serialportsettings_8cpp.html", null ],
    [ "serialportsettings.h", "serialportsettings_8h.html", "serialportsettings_8h" ],
    [ "signalglobalinformation.cpp", "signalglobalinformation_8cpp.html", null ],
    [ "signalglobalinformation.h", "signalglobalinformation_8h.html", "signalglobalinformation_8h" ],
    [ "spectrumchart.cpp", "spectrumchart_8cpp.html", null ],
    [ "spectrumchart.h", "spectrumchart_8h.html", "spectrumchart_8h" ]
];